# Generated by Django 5.1.2 on 2024-10-25 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0002_car_created_at_car_updated_at_carplaque_created_at_and_more'),
        ('perceptor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, db_column='date_paiement')),
                ('montant', models.FloatField(db_column='montant')),
                ('ref_car', models.ForeignKey(db_column='ref_car', on_delete=django.db.models.deletion.DO_NOTHING, to='car.car')),
                ('ref_perceptor', models.ForeignKey(db_column='ref_perceptor', on_delete=django.db.models.deletion.DO_NOTHING, to='perceptor.perceptor')),
            ],
            options={
                'db_table': 'tb_payment_tax',
            },
        ),
    ]
