# Generated by Django 5.1.2 on 2024-10-17 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_column='label', max_length=100)),
                ('tax_amount', models.IntegerField(db_column='tax_amount')),
            ],
            options={
                'db_table': 'tb_car_category',
            },
        ),
        migrations.CreateModel(
            name='Plaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_column='numero', max_length=20)),
                ('code_pays', models.CharField(db_column='code_pays', max_length=20)),
            ],
            options={
                'db_table': 'tb_plaque',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(db_column='nom_client', max_length=100)),
                ('category', models.ForeignKey(db_column='ref_category', on_delete=django.db.models.deletion.CASCADE, to='car.carcategory')),
            ],
            options={
                'db_table': 'tb_car',
            },
        ),
        migrations.CreateModel(
            name='CarPlaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(db_column='ref_car', on_delete=django.db.models.deletion.DO_NOTHING, to='car.car')),
                ('plaque', models.ForeignKey(db_column='ref_plaque', on_delete=django.db.models.deletion.DO_NOTHING, to='car.plaque')),
            ],
            options={
                'db_table': 'tb_car_plaque',
            },
        ),
    ]
