# Generated by Django 5.1.2 on 2024-10-25 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosteAttache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(db_column='designation', max_length=50)),
                ('localisation', models.CharField(db_column='localisation', max_length=100)),
            ],
            options={
                'db_table': 'tb_poste_attache',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(db_column='designation', max_length=100)),
            ],
            options={
                'db_table': 'tb_role',
            },
        ),
        migrations.CreateModel(
            name='Perceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(db_column='fullname', max_length=100)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=20)),
                ('ref_poste', models.ForeignKey(db_column='ref_poste', on_delete=django.db.models.deletion.DO_NOTHING, to='perceptor.posteattache')),
            ],
            options={
                'db_table': 'tb_perceptor',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('ref_perceptor', models.ForeignKey(db_column='ref_perceptor', on_delete=django.db.models.deletion.DO_NOTHING, to='perceptor.perceptor')),
            ],
            options={
                'db_table': 'tb_utilisateur',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_role', models.ForeignKey(db_column='ref_role', on_delete=django.db.models.deletion.DO_NOTHING, to='perceptor.role')),
                ('ref_user', models.ForeignKey(db_column='ref_user', on_delete=django.db.models.deletion.DO_NOTHING, to='perceptor.utilisateur')),
            ],
            options={
                'db_table': 'tb_user_role',
            },
        ),
    ]
